### ISSUE TITLE
To-Do : HOME

### ISSUE THREAD

**Issue by aymbot** [aymbot/Coffeetive#2]
**Main Task**
- [ ] Coffee Registration 
- [ ] Overview of todays added cup with timestamp

**Subtasks**
- [ ] Clean and stable BottomSheet fully functional
- [ ] Buttons for coffee cups (small, medium & large)
- [ ] Can delete added coffee cups
- [x] Add Button (FAB Button)
