### ISSUE TITLE
To-Do : NAVIGATION 

### ISSUE THREAD

**Issue by aymbot** [aymbot/Coffeetive#3]
**Main Task**
- [ ] Navigation fully completed

**Subtasks**
- [x] Add Home, About & Statistics
- [x] Navigation Drawer is well designed/interactive
- [x] Add About in a Options Menu
- [x] Buttons lead to appropriate Fragments
- [x] Implement Back Button Function
- [x] Implement Up Button Function
- [x] Implement feature that Navigation Drawer becomes Back Button in non-home Fragments
- [x] Color finished
- [ ] Design finished
